# .github/workflows/deploy_shiny_app.yml
# Nightly deployment of Shiny app after FINS data update

name: Deploy Shiny App After Data Update

on:
  schedule:
    # Run at 3:00 AM UTC = 8:00 PM PT (after FINS download at 7:30 PM PT)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering
  
  # Trigger after successful FINS data download
  workflow_run:
    workflows: ["Nightly FINS Data Download"]
    types:
      - completed

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    # Only run if FINS download succeeded (if using workflow_run trigger)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    
    env:
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          # Install packages individually to handle cuyem properly
          install.packages(c(
            "rsconnect",
            "shiny", 
            "shinydashboard",
            "DT",
            "plotly",
            "readr",
            "dplyr", 
            "ggplot2",
            "flextable",
            "htmltools",
            "lubridate",
            "tidyr",
            "stringr",
            "httr",
            "jsonlite"
          ), repos = "https://cran.rstudio.com/")
          
          # Install cuyem from Ryan Kinzer's GitHub repository
          if (!requireNamespace("remotes", quietly = TRUE)) {
            install.packages("remotes")
          }
          
          # Try to install cuyem - if it fails, continue anyway
          tryCatch({
            remotes::install_github("ryankinzer/cuyem", force = TRUE)
            cat("✅ Successfully installed cuyem package\n")
          }, error = function(e) {
            cat("⚠️ Could not install cuyem package:", conditionMessage(e), "\n")
            cat("Continuing deployment - app may need to handle missing cuyem gracefully\n")
          })
        shell: Rscript {0}

      - name: Deploy Shiny App
        run: |
          # Set up rsconnect credentials
          library(rsconnect)
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_NAME"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),  
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          
          # Deploy the app
          rsconnect::deployApp(
            appName = "LRW-Chinook-Summary",
            appTitle = "Lostine River Weir - Chinook Summary",
            appFiles = c(
              "app.R",
              "R/",
              "www/",
              "data/TrappingData.csv",
              "data/yearly_estimates.csv"
            ),
            forceUpdate = TRUE,
            launch.browser = FALSE
          )
          
          cat("Shiny app deployed successfully at:", format(Sys.time()), "\n")
        shell: Rscript {0}

      - name: Log deployment success
        run: |
          echo "✅ Deployment completed at: $(date)"
          echo "🌐 App URL: https://nptfisheries.shinyapps.io/LRW-Chinook-Summary/"